## v3

tests:
# The current format is: Branch : Strategy : [Tests]
  develop:
    coinflip:
      - "tests/test_tests.py:test_fail_twice_23"
      - "tests/test_tests.py:test_fail_once_1"
    90%:
      - "tests/test_tests.py:foo1"
  main: 
    90%:
      - "tests/test_tests.py:test_fail_once_1"
      - "tests/test_tests.py:test_fail_twice_23"
      - "tests/test_tests.py:foo2"

strategies:
  # What modes do we need?
  coinflip:
    at_least: 1
    out_of: 2
  90%:
    at_least: 1
    out_of: 10

prototypes: # Optional Prototype Section
  main: develop
  master: develop
